<%@ page import="java.sql.*" %>
<%
String userans = request.getParameter("useranswer");
String actualans = request.getParameter("actualanswer");
String email = request.getParameter("email");

if (!userans.equals(actualans)) {
    response.setContentType("text/html");
    out.println("<html>");
    out.println("<head>");
    out.println("<style>");
    out.println("body, h1, h2, h3, h4, h5, h6, p, ul, ol, li, table, th, td, form, input, select, textarea, button {");
    out.println("    margin: 0;");
    out.println("    padding: 0;");
    out.println("    border: 0;");
    out.println("    font-family: 'Arial', sans-serif;");
    out.println("    box-sizing: border-box;");
    out.println("}");
    out.println("body {");
    out.println("    background-color: #f4f4f4;");
    out.println("    display: flex;");
    out.println("    justify-content: center;");
    out.println("    align-items: center;");
    out.println("    height: 100vh;");
    out.println("    font-family: 'Arial', sans-serif;");
    out.println("}");
    out.println(".container {");
    out.println("    width: 100%;");
    out.println("    max-width: 400px;");
    out.println("    padding: 20px;");
    out.println("    background: #fff;");
    out.println("    box-shadow: 0 0 10px rgba(0,0,0,0.1);");
    out.println("    border-radius: 8px;");
    out.println("}");
    out.println(".form-title {");
    out.println("    margin-bottom: 20px;");
    out.println("    text-align: center;");
    out.println("    font-size: 24px;");
    out.println("    color: #333;");
    out.println("}");
    out.println(".input-group {");
    out.println("    margin-bottom: 15px;");
    out.println("    position: relative;");
    out.println("}");
    out.println(".input-group input,");
    out.println(".input-group select {");
    out.println("    width: 100%;");
    out.println("    padding: 10px;");
    out.println("    border: 1px solid #ddd;");
    out.println("    border-radius: 5px;");
    out.println("    transition: all 0.3s;");
    out.println("}");
    out.println(".input-group input:focus,");
    out.println(".input-group select:focus {");
    out.println("    border-color: #333;");
    out.println("    outline: none;");
    out.println("}");
    out.println(".btn {");
    out.println("    width: 100%;");
    out.println("    padding: 10px;");
    out.println("    background: #333;");
    out.println("    color: #fff;");
    out.println("    border: none;");
    out.println("    border-radius: 5px;");
    out.println("    cursor: pointer;");
    out.println("    transition: background 0.3s;");
    out.println("}");
    out.println(".btn:hover {");
    out.println("    background: #555;");
    out.println("}");
    out.println("</style>");
    out.println("</head>");
    out.println("<body>");
    out.println("<div class='container'>");
    out.println("<form action='forgotpassword.jsp' method='POST'>");
    out.println("<div class='form-title'><h1>Wrong answer to security question...retry?</h1></div>");
    out.println("<div class='input-group'><button type='submit' class='btn'>Proceed</button></div>");
    out.println("</form>");
    out.println("</div>");
    out.println("</body>");
    out.println("</html>");
} else {
    response.setContentType("text/html");
    out.println("<html>");
    out.println("<head>");
    out.println("<style>");
    out.println("body, h1, h2, h3, h4, h5, h6, p, ul, ol, li, table, th, td, form, input, select, textarea, button {");
    out.println("    margin: 0;");
    out.println("    padding: 0;");
    out.println("    border: 0;");
    out.println("    font-family: 'Arial', sans-serif;");
    out.println("    box-sizing: border-box;");
    out.println("}");
    out.println("body {");
    out.println("    background-color: #f4f4f4;");
    out.println("    display: flex;");
    out.println("    justify-content: center;");
    out.println("    align-items: center;");
    out.println("    height: 100vh;");
    out.println("    font-family: 'Arial', sans-serif;");
    out.println("}");
    out.println(".container {");
    out.println("    width: 100%;");
    out.println("    max-width: 400px;");
    out.println("    padding: 20px;");
    out.println("    background: #fff;");
    out.println("    box-shadow: 0 0 10px rgba(0,0,0,0.1);");
    out.println("    border-radius: 8px;");
    out.println("}");
    out.println(".input-group {");
    out.println("    margin-bottom: 15px;");
    out.println("    position: relative;");
    out.println("}");
    out.println(".input-group input,");
    out.println(".input-group select {");
    out.println("    width: 100%;");
    out.println("    padding: 10px;");
    out.println("    border: 1px solid #ddd;");
    out.println("    border-radius: 5px;");
    out.println("    transition: all 0.3s;");
    out.println("}");
    out.println(".input-group input:focus,");
    out.println(".input-group select:focus {");
    out.println("    border-color: #333;");
    out.println("    outline: none;");
    out.println("}");
    out.println(".btn {");
    out.println("    width: 100%;");
    out.println("    padding: 10px;");
    out.println("    background: #333;");
    out.println("    color: #fff;");
    out.println("    border: none;");
    out.println("    border-radius: 5px;");
    out.println("    cursor: pointer;");
    out.println("    transition: background 0.3s;");
    out.println("}");
    out.println(".btn:hover {");
    out.println("    background: #555;");
    out.println("}");
    out.println("</style>");
    out.println("</head>");
    out.println("<body>");
    out.println("<div class='container'>");
    out.println("<form action='UpdateNewPassword' method='POST'>");
    out.println("<input type='hidden' name='email' value='" + email + "'>");
    out.println("<div class='input-group'><label>New Password:</label><input type='password' name='pass' placeholder='Enter new password'></div>");
    out.println("<div class='input-group'><label>Confirm Password:</label><input type='password' name='confpass' placeholder='Confirm new password'></div>");
    out.println("<div class='input-group'><button type='submit' class='btn'>Update password</button></div>");
    out.println("</form>");
    out.println("</div>");
    out.println("</body>");
    out.println("</html>");
}
%>
